spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/lecture-management-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog/changelog-master.xml
    enabled: true